name: Run tests and upload coverage

on: 
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest --cov --cov-branch --cov-report=xml
          # pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 2
# 
#       - name: Set up Python
#         uses: actions/setup-python@v4
# 
#       - name: Install dependencies
#         run: pip install pytest pytest-cov
# 
#       - name: Installing BowshockPy dependencies
#         run: pip install -r requirements.txt
# 
#       - name: Run tests
#         run: pytest --cov --cov-branch --cov-report=xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
